### ISSUE TITLE
Create own Salat-context

### ISSUE THREAD

**Issue by tmbo** [Mironor/Play-2.0-Scala-MongoDb-Salat-exemple#1]
If the application grows, you will run into ClassCastExceptions if you don't use our own salat-context
(it's because of plays dynamic class reloading and stuff). The context should look like https://github.com/andypetrella/classloading-problem/blob/master/app/models/salatctx.scala.

**Comment by Mironor** [comment]
I'm sorry it took me so long to reply to your message.

What I tried to do was to put in the internet few files for the "hello world" application using mongo db as there was nothing on the subject. 

I think it will be more interesting to keep at the minimum the number of files, tell about the context problem in the readme file and give a link to a more complex similar project (like this one https://github.com/bjartek/computer-database-mongo ). 

Nevertheless, thanks for the help, I appreciate it a lot
